tmp.insert(std::pair<std::string, std::vector<std::string>("text/html", "html htm shtml"));
tmp.insert(std::pair<std::string, std::vector<std::string>("text/css", "css"));
tmp.insert(std::pair<std::string, std::vector<std::string>("text/xml", "xml"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/gif", "gif"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/jpeg", "jpeg jpg"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/javascript", "js"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/atom+xml", "atom"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/rss+xml", "rss"));
tmp.insert(std::pair<std::string, std::vector<std::string>("text/mathml", "mml"));
tmp.insert(std::pair<std::string, std::vector<std::string>("text/plain", "txt"));
tmp.insert(std::pair<std::string, std::vector<std::string>("text/vnd.sun.j2me.app-descriptor", "jad"));
tmp.insert(std::pair<std::string, std::vector<std::string>("text/vnd.wap.wml", "wml"));
tmp.insert(std::pair<std::string, std::vector<std::string>("text/x-component", "htc"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/png", "png"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/tiff", "tif tiff"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/vnd.wap.wbmp", "wbmp"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/x-icon", "ico"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/x-jng", "jng"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/x-ms-bmp", "bmp"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/svg+xml", "svg svgz"));
tmp.insert(std::pair<std::string, std::vector<std::string>("image/webp", "webp"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/font-woff", "woff"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/java-archive", "jar war ear"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/json", "json"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/mac-binhex40", "hqx"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/msword", "doc"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/pdf", "pdf"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/postscript", "ps eps ai"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/rtf", "rtf"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.apple.mpegurl", "m3u8"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.ms-excel", "xls"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.ms-fontobject", "eot"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.ms-powerpoint", "ppt"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.wap.wmlc", "wmlc"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.google-earth.kml+xml", "kml"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.google-earth.kmz", "kmz"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-7z-compressed", "7z"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-cocoa", "cco"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-java-archive-diff", "jardiff"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-java-jnlp-file", "jnlp"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-makeself", "run"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-perl", "pl pm"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-pilot", "prc pdb"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-rar-compressed", "rar"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-redhat-package-manager", "rpm"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-sea", "sea"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-shockwave-flash", "swf"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-stuffit", "sit"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-tcl", "tcl tk"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-x509-ca-cert", "der pem crt"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/x-xpinstall", "xpi"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/xhtml+xml", "xhtml"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/xspf+xml", "xspf"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/zip", "zip"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/octet-stream", "bin exe dll"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/octet-stream", "deb"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/octet-stream", "dmg"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/octet-stream", "iso img"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/octet-stream", "msi msp msm"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"));
tmp.insert(std::pair<std::string, std::vector<std::string>("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx"));
tmp.insert(std::pair<std::string, std::vector<std::string>("audio/midi", "mid midi kar"));
tmp.insert(std::pair<std::string, std::vector<std::string>("audio/mpeg", "mp3"));
tmp.insert(std::pair<std::string, std::vector<std::string>("audio/ogg", "ogg"));
tmp.insert(std::pair<std::string, std::vector<std::string>("audio/x-m4a", "m4a"));
tmp.insert(std::pair<std::string, std::vector<std::string>("audio/x-realaudio", "ra"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/3gpp", "3gpp 3gp"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/mp2t", "ts"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/mp4", "mp4"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/mpeg", "mpeg mpg"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/quicktime", "mov"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/webm", "webm"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/x-flv", "flv"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/x-m4v", "m4v"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/x-mng", "mng"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/x-ms-asf", "asx asf"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/x-ms-wmv", "wmv"));
tmp.insert(std::pair<std::string, std::vector<std::string>("video/x-msvideo", "avi"));